[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymcdebug"
version = "1.0.0"
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
requires-python = ">= 3.8"
dependencies = [
  "arviz",
  "rich",
  "pymc",
  "requests",
  "simplejson",
  "numpy",
]